### ISSUE TITLE
Being able to set the VM memory size permanently

### ISSUE THREAD

**Issue by mickours** [oar-team/nixos-compose#4]
Hi!

My composition needs VMs with 2GB of memory, but the default value is 1GB. I found out that I can set the VM memory using the `MEM` environment variable, but this is not very reproducible and I'd like to have a more permanent way to set this value.

Is it possible to set it in the composition directly? Or in the setup.toml?

Thanks!

**Comment by jojothan** [comment]
Hi !

I remember using this attribute in some compositions to set the memory size of the VM.
```
virtualisation.memorySize = 3000;
```

**Comment by mickours** [comment]
This is not working anymore... 

After some discussion with @augu5te, because VM specific options should not go into the composition, I'll try to add a new `node-config` option to `nxc start` to specify the resource of each nodes and the Qemu options to mount the volumes. This file should be generated by an external tool at first.

It includes the memory, and the CPU core, but also the disk setup. For example:
```yaml
# Will be append to the deployments.json to be use inside the composition to mount the disk
deployments:
  volumes-config:
      nodes-1:
        path: /dev/hda1
        mount: /var
 
# Will be use by the start command to append options for each node
quemuOpts: 
  node-1: -drive file=/tmp/disks/diskID1234.qcow -m=2G
  node-2: -drive file=/tmp/disks/diskID4567.qcow -m=2G
  server: -drive file=/tmp/disks/diskID0987.qcow -cpu=3
```
An external tool should be call to create the disks before the VM starts and remove disks once stopped.
